project_id = "wdqsgswrkrxjeesahshc"

[functions.spider-identify]
verify_jwt = true

[functions.reset-history]
verify_jwt = true

[functions.auto-battle]
verify_jwt = true

[functions.export-email-list]
verify_jwt = true
